// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHcz-VrDGAB-U84tVP1azURfRRkURNH6Q',
    appId: '1:1069755541762:web:679821b763870ca5e1fa1b',
    messagingSenderId: '1069755541762',
    projectId: 'union-shop-ee9d5',
    authDomain: 'union-shop-ee9d5.firebaseapp.com',
    storageBucket: 'union-shop-ee9d5.firebasestorage.app',
    measurementId: 'G-K9QG799TS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfrSs7KT-6-QQgtRnfrN67kUPtd-eL00',
    appId: '1:1069755541762:android:9ab470675d363fa9e1fa1b',
    messagingSenderId: '1069755541762',
    projectId: 'union-shop-ee9d5',
    storageBucket: 'union-shop-ee9d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjyWhg1ZxctipsDpixCnfr1VXE7-K7Ho',
    appId: '1:1069755541762:ios:838109faacbe9733e1fa1b',
    messagingSenderId: '1069755541762',
    projectId: 'union-shop-ee9d5',
    storageBucket: 'union-shop-ee9d5.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjyWhg1ZxctipsDpixCnfr1VXE7-K7Ho',
    appId: '1:1069755541762:ios:838109faacbe9733e1fa1b',
    messagingSenderId: '1069755541762',
    projectId: 'union-shop-ee9d5',
    storageBucket: 'union-shop-ee9d5.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHcz-VrDGAB-U84tVP1azURfRRkURNH6Q',
    appId: '1:1069755541762:web:ffa28b8703637e97e1fa1b',
    messagingSenderId: '1069755541762',
    projectId: 'union-shop-ee9d5',
    authDomain: 'union-shop-ee9d5.firebaseapp.com',
    storageBucket: 'union-shop-ee9d5.firebasestorage.app',
    measurementId: 'G-0XYNFBL77H',
  );
}
